---
model:
  num_features: 2
  hidden_channels: 64
  filter_size: 2 # K
optim: 
  initial_lr: 0.01
  lr_decay_ratio: 0.1
  lr_decay_milestones: [20, 30, 40, 50]
  epsilon: 0.001
train: 
  epochs: 100
  max_grad_norm: 5